### ISSUE TITLE
구매 목록 기능 구현

### ISSUE THREAD

**Issue by jinsu868** [Palgona/Backend#62]
## Description

- 구매 목록 기능을 구현한다.

## Todo

- [x] 구매 목록 추가 기능
- [x] 구매 목록 조회 기능

## Discussion
구매 기능을 구현하려고 하는데
1) 입찰 상태가 성공으로 바뀌는 시점에 바로 결제되고 구매 목록 추가하기
2) 입찰 상태가 성공으로 바뀌고 나서 최고 입찰자가 구매 확정을 누르면 결제되게 하기 (입찰 성공 -> 구매 확정 deadline 정해놓기, deadline 지나거나 취소하면 위약금)
최고 입찰자가 취소하게 되면 판매자는 상품을 재등록하고 다시 입찰 과정을 거쳐서 상품을 판매해야 함.
저는 2번이 좋을 것 같은데 어떻게 생각하시나요?

**Comment by JangWooJin1** [comment]
저도 안전 시스템을 위해 2번 방식으로 진행하는게 좋아보여요!
