### ISSUE TITLE
유저 마일리지 필드

### ISSUE THREAD

**Issue by jinsu868** [Palgona/Backend#74]
## Description

마일리지를 Member 필드에 가지고 있으니까 충돌이 생각보다 많이 생길 것 같아요.
(구매확정이나 입찰이 완료될 때 변경 쿼리 나가는데 이때 유저가 마일리지 변경)
이대로 갈지 아니면 수정할지 정해지면 테스트 코드랑 같이 수정해서 올릴게요

의견 남겨주세요~

**Comment by janghoosa** [comment]
> 마일리지를 Member 필드에 가지고 있으니까 충돌이 생각보다 많이 생길 것 같아요.

member에서 다른 트랜잭션이 많아서 충돌이 생긴다는 말씀이실까요?

**Comment by jinsu868** [comment]
네네 member의 마일리지를 동시에 변경하는 상황 말씀드린거에요

1. 입찰 성공 로직에서 최고 입찰가를 제외한 모든 입찰자의 마일리지 복구
  - 이 상황에서 맴버가 마일리지 충전, 다른 상품에 대한 입찰, 판매중인 상품이 구매 확정됐을 때 충돌
2. 입찰 확정에서 purchase를 저장하면서 최고 입찰자(Member)에 공유락 걸림.
  - 이 때 마찬가지로 마일리지 변경될 수 있는 경우들
3. 구매 확정, 취소 및 기타 마일리지 변경될 수 있는 요소들

마일리지 변경이 단순 충전, 판매, 구매면 문제가 없을 것 같은데 입찰 때문에 스케줄링되면서 다른 변경 사항들이 겹치는 것 같네요.
스케줄링 주기가 길면 괜찮을 것 같은데 지금 30초라 생각보다 많이 발생할 것 같아요.

**Comment by janghoosa** [comment]
마일리지는 따로 분리해내도 모든 상황에서 같은 트랜잭션과 같은 락이 걸리지 않을까요?
동시에 여러명의 작업은 모두 필요해서 트랙잭션 순서대로 진행하면 문제는 없을 것 같고요.
member에서 자주 바뀔 내용이 mileage밖에 없어서 저는 따로 분리하지않고 지금처럼 유지해도 될것 같은데 어떻게 생각하시나요?

스케줄링은 1분단위로 매분 0초 마다 작업하는게 나아보여요.

**Comment by jinsu868** [comment]
네 그렇죠 마일리지는 분리해도 락 걸리는 건 동일하죠.
제가 생각했던 건 마일리지뿐 아니라 member에 대한 락이 걸리는 거였는데
> member에서 자주 바뀔 내용이 mileage밖에 없어서 저는 따로 분리하지 않고 지금처럼 유지해도 될 것 같은데 어떻게 생각하시나요?

생각해 보니까 말씀 주신 것처럼 마일리지 변경 아니면 member가 바뀔 일이 거의 없겠네요.

스케줄링은 지금 Bidding은 30초, Purchase는 5분이었던 것 같은데 둘 다 1분으로 수정할까요?

**Comment by janghoosa** [comment]
넵, 1분 단위로 진행하는게 좋아보여요~~!
좋은 고민 생각해주셔서 감사해요 👍

**Comment by jinsu868** [comment]
태준님 덕분에 많이 배워가네요 ㅎㅎ 
피드백 감사합니다

**Comment by janghoosa** [comment]
저도 진수님께 많이 배우는걸요!
빨리 작업해서 pr 올려드릴게요... 작업량은 맞춰야할듯 싶어요ㅋㅋㅋ
